# Generated by Django 3.2.9 on 2021-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Instructor Name', 'Instructor Name'), ('Course Number', 'Course Number'), ('Course', 'Course')], max_length=50)),
                ('Course_Number', models.IntegerField(blank=True, default='', max_length=10)),
                ('Instructor_Name', models.CharField(default='', max_length=50)),
                ('Duration', models.FloatField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
