# Generated by Django 3.2.9 on 2021-11-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('Course Number', 'Course Number'), ('Instructor Name', 'Instructor Name'), ('Course', 'Course')], max_length=50),
        ),
    ]
