# Generated by Django 3.2.9 on 2021-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20211104_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('HTML/CSS', 'HTML/CSS')], max_length=50),
        ),
    ]
