# Generated by Django 3.2.9 on 2021-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_alter_djangoclasses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(blank=True, default='100'),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('Python', 'Python'), ('JavaScript', 'JavaScript')], max_length=50),
        ),
    ]
