# Generated by Django 3.2.9 on 2021-11-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20211104_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(blank=True, default='1:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('HTML/CSS', 'HTML/CSS')], max_length=50),
        ),
    ]
